# Generated by Django 4.2.9 on 2024-02-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_evento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]
