# Generated by Django 4.2.9 on 2024-02-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_evento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
